---
driver:
  name: ec2
  region: ap-southeast-2
  instance_type: t2.micro
  subnet_id: subnet-deadbeef
  security_group_ids: [sg-1337d00d]
  aws_ssh_key_id: personal
  user_data: files/user_data.txt
  interface: private
  block_device_mappings:
    - device_name: /dev/sda1
      ebs:
        volume_size: 64
        delete_on_termination: true

provisioner:
  name: chef_solo

platforms:
  - name: windows-2012r2

transport:
  ssh_key: ~/.ssh/personal

suites:
  - name: default
    run_list:
      - recipe[windows-services::default]
    attributes:
