---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: win2012r2chef

suites:
  - name: default
    run_list:
      - recipe[windows-services::default]
    attributes:
