name 'windows-services'
maintainer 'Tristan Morgans'
maintainer_email 'tristan@vibrato.com.au'
license 'all_rights'
description 'Installs/Configures windows-services'
long_description 'Installs/Configures windows-services'
version '0.1.0'
